### ISSUE TITLE
Update from 2.3.0 to 2.4.0 fails

### ISSUE THREAD

**Issue by fzieris** [thephpleague/oauth2-client#752] opened 2018-11-21 22:54 UTC
Context: Symfony project with dependency `"league/oauth2-google": "^2.2"`, which in turn depends on oauth2-client.

So far, I had oauth2-client installed in version 2.3.0, but upon `composer update` I get the following error message, after the upgrade to 2.4.0:

> Fatal error: Declaration of League\OAuth2\Client\Provider\Google::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessToken $token) must be compatible with League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessTokenInterface $token) in G:\XXX\vendor\league\oauth2-google\src\Provider\Google.php on line 11

**Comment by fzieris** [comment] 2018-11-21 23:13
Hotfix in composer.json 

```diff
    "conflict": {
+        "league/oauth2-client": "2.4.0"
    },
```

**Comment by ramsey** [comment] 2018-11-22 00:12
Gah! I didn’t think that would break BC. I was wrong. I’ll get a fix out within 24 hours. Thanks!

**Comment by senyahnoj** [comment] 2018-11-22 14:16
Thanks for your prompt action on resolving this. I have the exact same issue with pviojo/oauth2-keycloak

**Comment by ramsey** [comment] 2018-11-22 16:29
Nevermind. I am an idiot. I was extending the wrong class. 🤦‍♂️

**Closed** 2018-11-22 18:20 UTC

**Comment by ramsey** [comment] 2018-11-22 18:37
Please check release 2.4.1 and confirm that it fixes this issue. Thanks!

**Comment by senyahnoj** [comment] 2018-11-23 08:40
I confirm that it's fixed it for me. Thanks again

**Comment by holtkamp** [comment] 2018-11-23 09:53
Confirmed! Thanks!

**Comment by holtkamp** [comment] 2019-11-18 10:05
@ramsey since it breaks compatibility, a new major release is "required" to be able to use the `AccessTokenInterface` instead of the `AccesToken`. Are there concrete plans for such a major release already?

**Comment by ramsey** [comment] 2019-11-18 18:48
@holtkamp I missed that comment from a year ago. So, version `2.4.1` introduced a BC break, and it should have, instead, been released in a new major version? Since it's been a year, is this still a concern?

**Comment by holtkamp** [comment] 2019-11-18 21:01
@ramsey ooh, no worries, the comment was from today when I was navigating some code and saw a ```AccessToken``` being passed around instead of an ```AccessTokenInterface```, that is why I "revived" this. It is not an issue, but it would be more elegant to only work with an ```AccessTokenInterface```, right?
