### ISSUE TITLE
GuzzleHttp\Exception\RequestException (cuRL error 56: SSL read: error)

### ISSUE THREAD

**Issue by triswan** [thephpleague/oauth2-client#707] opened 2018-05-14 10:21 UTC
I used this library on laravel 5.4 for over six months
It had been working normally until yesterday, it showed error: 

![image](https://user-images.githubusercontent.com/17003450/40032650-2e8b4e00-581f-11e8-85af-f1bc5cffaab1.png)

```
GuzzleHttp\Exception\RequestException
cURL error 56: SSL read: errno -5961 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I tried in another machine, same exception with slightly different message:

```
GuzzleHttp\Exception\RequestException
cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

with standard php-curl extension, the request was successful and returned correct response:

```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_PORT => "{port}",
  CURLOPT_URL => "https://{url}:{port}/token",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "grant_type=client_credentials&client_id={myclientid}&client_secret={myclientsecret}",
  CURLOPT_HTTPHEADER => array(
    "cache-control: no-cache",
    "content-type: application/x-www-form-urlencoded",
    "postman-token: 17ee31bc-e6af-2eee-7d54-6ede67ba1c4b"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

I've been wondering if there was a SSL configuration change on the server side, but after I updated the library to latest version (2.3), the error didn't go away

Any help is very appreciated...
Thanks

**Comment by Mashpy** [comment] 2018-12-07 13:20
same here.

**Comment by xhava** [comment] 2019-01-16 12:43
same here, some solution?

**Comment by ramsey** [comment] 2020-10-28 20:23
I'm at a loss for why this might happen. The only thing I can think of is that cURL when used through Guzzle is doing more strict verification of the SSL certificate than is happening when you use php-curl directly.

I'll close this for now, but if it's still an issue, please re-open and let me know. First, though, try debugging this through Guzzle itself to see if you can get a successful response there. If so, then that indicates that a problem might exist in league/oauth2-client. If not, then the problem is probably a Guzzle configuration issue.

**Closed by ramsey** 2020-10-28 20:23 UTC
